# Generated by Django 4.0.1 on 2022-01-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_alter_post_options_post_image_post_share_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='share_user',
            new_name='shared_user',
        ),
    ]
